name: ðŸš€ Deploy Webeez Legacy (Theme & Plugin Only)

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy to Live Server
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v4
      - name: ðŸŽ¨ Deploy Webeez Theme
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          local-dir: ./wp-content/themes/webeez/
          server-dir: ./webeez.gr/public_html/wp-content/themes/webeez/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.DS_Store
            **/assets/src/** #
      - name: ðŸ§© Deploy Webeez Addons Plugin
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          local-dir: ./wp-content/plugins/webeez-addons/
          server-dir: ./webeez.gr/public_html/wp-content/plugins/webeez-addons/
          exclude: |
            **/.git*
            **/.git*/**
            **/.DS_Store
